/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoardRouteRouteImport } from './routes/_board/route'
import { Route as BoardIndexRouteImport } from './routes/_board/index'
import { Route as BoardNotesIndexRouteImport } from './routes/_board/notes/index'
import { Route as BoardPinnedIndexRouteImport } from './routes/_board/pinned/index'

const BoardRouteRoute = BoardRouteRouteImport.update({
  id: '/_board',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardRouteRoute,
} as any)
const BoardNotesIndexRoute = BoardNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => BoardRouteRoute,
} as any)
const BoardPinnedIndexRoute = BoardPinnedIndexRouteImport.update({
  id: '/pinned/',
  path: '/pinned/',
  getParentRoute: () => BoardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof BoardIndexRoute
  '/notes/': typeof BoardNotesIndexRoute
  '/pinned/': typeof BoardPinnedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof BoardIndexRoute
  '/notes': typeof BoardNotesIndexRoute
  '/pinned': typeof BoardPinnedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_board': typeof BoardRouteRouteWithChildren
  '/_board/': typeof BoardIndexRoute
  '/_board/notes/': typeof BoardNotesIndexRoute
  '/_board/pinned/': typeof BoardPinnedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notes/' | '/pinned/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notes' | '/pinned'
  id: '__root__' | '/_board' | '/_board/' | '/_board/notes/' | '/_board/pinned/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BoardRouteRoute: typeof BoardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_board': {
      id: '/_board'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BoardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_board/': {
      id: '/_board/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof BoardRouteRoute
    }
    '/_board/notes/': {
      id: '/_board/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof BoardNotesIndexRouteImport
      parentRoute: typeof BoardRouteRoute
    }
    '/_board/pinned/': {
      id: '/_board/pinned/'
      path: '/pinned'
      fullPath: '/pinned/'
      preLoaderRoute: typeof BoardPinnedIndexRouteImport
      parentRoute: typeof BoardRouteRoute
    }
  }
}

interface BoardRouteRouteChildren {
  BoardIndexRoute: typeof BoardIndexRoute
  BoardNotesIndexRoute: typeof BoardNotesIndexRoute
  BoardPinnedIndexRoute: typeof BoardPinnedIndexRoute
}

const BoardRouteRouteChildren: BoardRouteRouteChildren = {
  BoardIndexRoute: BoardIndexRoute,
  BoardNotesIndexRoute: BoardNotesIndexRoute,
  BoardPinnedIndexRoute: BoardPinnedIndexRoute,
}

const BoardRouteRouteWithChildren = BoardRouteRoute._addFileChildren(
  BoardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  BoardRouteRoute: BoardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
